# Generated by Django 6.0.6 on 2026-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('otro', 'Otro')], max_length=50)),
            ],
            options={
                'verbose_name': 'Representante legal',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_socioeconomico', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=20)),
                ('nivel_actividad', models.CharField(choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='baja', max_length=20)),
                ('institucion', models.CharField(blank=True, help_text='Colegio o fundación', max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.eps')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.representantelegal')),
            ],
            options={
                'verbose_name': 'Paciente',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RestriccionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('medico_tratante', models.CharField(blank=True, max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='pacientes.paciente')),
            ],
        ),
    ]
