# Generated by Django 6.0.6 on 2026-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valoracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de alimento',
                'verbose_name_plural': 'Categorías de alimentos',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disponible_pae', models.BooleanField(default=True)),
                ('alergeno', models.BooleanField(default=False, help_text='¿Es un alérgeno común?')),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='recomendaciones.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Alimento',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupos_alimentarios', models.TextField()),
                ('detalle', models.TextField()),
                ('detalle_ia', models.TextField(blank=True, help_text='Texto generado por Gemini')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('alimentos', models.ManyToManyField(blank=True, to='recomendaciones.alimento')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacion', to='valoracion.consulta')),
            ],
            options={
                'verbose_name': 'Recomendación',
            },
        ),
    ]
