# Generated by Django 6.0.6 on 2026-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaExperto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('imc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edad_min', models.IntegerField(blank=True, null=True)),
                ('edad_max', models.IntegerField(blank=True, null=True)),
                ('nivel_se', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('cualquiera', 'Cualquiera')], default='cualquiera', max_length=20)),
                ('nivel_actividad', models.CharField(choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta'), ('cualquiera', 'Cualquiera')], default='cualquiera', max_length=20)),
                ('clasificacion', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('prioridad', models.IntegerField(default=0, help_text='Mayor número = se evalúa primero')),
            ],
            options={
                'verbose_name': 'Regla experto',
                'verbose_name_plural': 'Reglas experto',
                'ordering': ['-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc_calculado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clasificacion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('validado_por_nutricionista', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
                ('regla_activada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valoracion.reglaexperto')),
            ],
            options={
                'verbose_name': 'Consulta',
                'ordering': ['-fecha'],
            },
        ),
    ]
