# Generated by Django 6.0.6 on 2026-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
